export const FETCHING_SYMBOLS = 'FETCHING_SYMBOLS';
export const FETCHING_SYMBOLS_SUCCESS = 'FETCHING_SYMBOLS_SUCCESS';
export const FETCHING_SYMBOLS_FAIL = 'FETCHING_SYMBOLS_FAIL';

export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const CHANGE_FROM = 'CHANGE_FROM';
export const CHANGE_TO = 'CHANGE_TO';
