export const FETCHING_SYMBOLS = 'FETCHING_SYMBOLS';
export const FETCHING_SYMBOLS_SUCCESS = 'FETCHING_SYMBOLS_SUCCESS';
export const FETCHING_SYMBOLS_FAIL = 'FETCHING_SYMBOLS_FAIL';

export const CHANGING_CURRENCY = 'CHANGING_CURRENCY';
export const CHANGING_FROM = 'CHANGING_FROM';
export const CHANGING_TO = 'CHANGING_TO';

export const CONVERTING_CURRENCIES = 'CONVERTING_CURRENCIES';
export const CONVERTING_CURRENCIES_SUCCESS = 'CONVERTING_CURRENCIES_SUCCESS';
export const CONVERTING_CURRENCIES_FAIL = 'CONVERTING_CURRENCIES_FAIL';
